# compose.override.yml
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_MAP_STYLE_URL: ${NEXT_PUBLIC_MAP_STYLE_URL}
    environment:
      NEXT_PUBLIC_MAP_STYLE_URL: ${NEXT_PUBLIC_MAP_STYLE_URL}
      API_BASE: http://api:3001
    ports: ["3000:3000"]
    depends_on:
      api:
        condition: service_started

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
    ports: ["3001:3001"]
    depends_on:
      db:
        condition: service_healthy

  db:
    ports: ["5432:5432"]
