name: CI/CD

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write   # needed to push to GHCR with GITHUB_TOKEN

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Compute lowercase owner/repo and export image names for later steps
      - name: Set image names (lowercase)
        shell: bash
        env:
          OWNER: ${{ github.repository_owner }}
          REPO:  ${{ github.repository }}
        run: |
          OWNER_LC=$(echo "$OWNER" | tr '[:upper:]' '[:lower:]')
          REPO_LC=$(echo "${REPO##*/}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_WEB=ghcr.io/${OWNER_LC}/${REPO_LC}-web" >> $GITHUB_ENV
          echo "IMAGE_API=ghcr.io/${OWNER_LC}/${REPO_LC}-api" >> $GITHUB_ENV

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build & push the WEB image
      - name: Build & push WEB
        uses: docker/build-push-action@v6
        with:
          context: ./web
          push: true
          tags: |
            ${{ env.IMAGE_WEB }}:latest
            ${{ env.IMAGE_WEB }}:${{ github.sha }}

      # Build & push the API image
      - name: Build & push API
        uses: docker/build-push-action@v6
        with:
          context: ./api
          push: true
          tags: |
            ${{ env.IMAGE_API }}:latest
            ${{ env.IMAGE_API }}:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /opt/pum
            # login only needed if your GHCR packages are private
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin
            docker compose pull
            docker compose up -d --remove-orphans
            docker image prune -f
